apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: patnaikshekhar/kubedashboard:0.0.1
      serviceAccountName: dashboard-sa