apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-role
rules:
- apiGroups:
  - ""
  - "apps"
  - "batch"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-role-binding
subjects:
- kind: ServiceAccount
  name: dashboard-sa
  namespace: dashboard
roleRef:
  kind: ClusterRole
  name: dashboard-role
  apiGroup: rbac.authorization.k8s.io


